---
title: "2. descriptive_02 27 25"
output: html_document
date: "2025-02-27"
---
# Notes
This code generates data for Table 1. 

# Loading packages
```{r packages, include = FALSE}
library(haven) # inputting data 
library(tidyverse) # data mgmt
library(psych) # easy summary statistics
library(DT) # data tables
library(tableone) # easy table 1 
library(kableExtra) # format kable objects 
library(naniar) # for missingness 
library(survey) # for MSMs 
library(nnet) # multinormal regression
library(cobalt) # examining covariate balance
library(gt) # nice tables
library(gtsummary) # nice tables 
library(broom) # making output nice
library(sjPlot) # nice cross tabs
library(openxlsx) # outputting excel sheets 
options(max.print=100000)
```
```{css scroll box for code, include = FALSE}
pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 100px;
}
```

# Loading data
```{r data, include = FALSE}
load(file = "./analysis data/causmed.Rdata") # n=3592, v=69
names(causmed) %>% view()
```

## Formatting data for presentation
```{r time diff, include = FALSE}
causmed2 <- causmed %>%
  mutate(agediff12 = age_2 - age_1) %>%
  mutate(gender_fct = case_when(
    gender == 0 ~ "Men",
    gender == 1 ~ "Women",
    TRUE ~ NA)) %>%
  mutate(gender_fct = factor(gender_fct, 
                             levels = c("Men", "Women"))) %>%
  mutate(haswmhv2_fct = case_when(
    haswmhv2 == 1 ~ "Has WMHV at Visit 2",
    haswmhv2 == 0 ~ "No WMHV at Visit 2",
    TRUE ~ NA)) %>% 
  mutate(haswmhv2_fct = factor(haswmhv2_fct, 
                               levels = c("Has WMHV at Visit 2",
                                          "No WMHV at Visit 2"))) %>%
  mutate(hasabv2_fct = case_when(
    hasabv2 == 1 ~ "Has Amyloid-PET at Visit 2",
    hasabv2 == 0 ~ "No Amyloid-PET at Visit 2",
    TRUE ~ NA)) %>% 
  mutate(hasabv2_fct = factor(hasabv2_fct, 
                              levels = c("Has Amyloid-PET at Visit 2",
                                         "No Amyloid-PET at Visit 2"))) %>%
  mutate(hasmttau2_fct = case_when(
    hasmttauv2 == 1 ~ "Has MTL Tau-PET at Visit 2",
    hasmttauv2 == 0 ~ "No MTL Tau-PET at Visit 2",
    TRUE ~ NA)) %>% 
  mutate(hasmttau2_fct = factor(hasmttau2_fct, 
                                levels = c("Has MTL Tau-PET at Visit 2",
                                           "No MTL Tau-PET at Visit 2"))) %>%
  mutate(hasctv2_fct = case_when(
    hasctv2 == 1 ~ "Has AD meta-ROI CT at Visit 2",
    hasctv2 == 0 ~ "No AD meta-ROI CT at Visit 2",
    TRUE ~ NA)) %>% 
  mutate(hasctv2_fct = factor(hasctv2_fct, 
                              levels = c("Has AD meta-ROI CT at Visit 2",
                                         "No AD meta-ROI CT at Visit 2"))) %>%
  mutate(icv_1_cm3 = (icv_1/1000)) %>%
  mutate(takes_BP_meds = factor(takes_BP_meds,
                                levels = c(0, 1)))

# n=3592, v=74

# checking variables
summary(causmed2$haswmhv2_fct)
summary(causmed2$hasabv2_fct)
summary(causmed2$hasmttau2_fct)
summary(causmed2$hasctv2_fct)
summary(causmed2$icv_1_cm3)
```

# Table 1, for those with WMHV at visit 2
```{r table 1 wmhv, include = FALSE}
tbl1_wmhv <- causmed2 %>%
  filter(haswmhv2_fct == "Has WMHV at Visit 2") %>% 
  tbl_summary(include = c(# demographics
                          age_1, ethnicity, gender_fct, agediff12,
                          # social
                          edu, hasnoinsurance, income, socsupptot,
                          # clinical/behavioral variables
                          smkever, bmi, sbpavg, dbpavg, rapa_1_total,
                          rapa_2_total, gds_total, takes_BP_meds, has_htn,
                          # medical history
                          cdx_dep, cdx_cog, cdx_dyslipid, cdx_cvd, cdx_dm,
                          # labs 
                          ldl, gluc, a1c, egfr_nonaa, egfr_aa, choltot,
                          apoe4_positivity,
                          # imaging vars
                          wmhv_2, absuvr_2, taumedtempsuvr_2, ctmetaroi_2,
                          icv_1_cm3),
              type = list(
                age_1 ~ "continuous",
                ethnicity ~ "categorical", 
                gender_fct ~ "categorical",
                edu ~ "continuous", 
                agediff12 ~ "continuous",
                hasnoinsurance ~ "dichotomous", 
                income ~ "continuous", 
                socsupptot ~ "continuous",
                smkever  ~ "dichotomous", 
                bmi ~ "continuous", 
                sbpavg ~ "continuous", 
                dbpavg ~ "continuous", 
                rapa_1_total ~ "continuous", 
                rapa_2_total ~ "continuous", 
                gds_total ~ "continuous", 
                takes_BP_meds  ~ "dichotomous", 
                has_htn  ~ "dichotomous",
                cdx_dep  ~ "dichotomous", 
                cdx_cog  ~ "dichotomous", 
                cdx_dyslipid  ~ "dichotomous", 
                cdx_cvd  ~ "dichotomous", 
                cdx_dm  ~ "dichotomous",
                ldl ~ "continuous", 
                gluc ~ "continuous", 
                a1c ~ "continuous", 
                egfr_nonaa ~ "continuous", 
                egfr_aa ~ "continuous", 
                choltot ~ "continuous",
                apoe4_positivity  ~ "dichotomous",
                wmhv_2 ~ "continuous", 
                absuvr_2 ~ "continuous", 
                taumedtempsuvr_2 ~ "continuous", 
                ctmetaroi_2 ~ "continuous",
                icv_1_cm3 ~ "continuous"),
              value = list(
                hasnoinsurance ~ 1, 
                takes_BP_meds ~ 1, 
                has_htn ~ 1,
                cdx_dep ~ 1, 
                cdx_cog ~ 1, 
                cdx_dyslipid ~ 1, 
                cdx_cvd ~ 1, 
                cdx_dm ~ 1,
                apoe4_positivity ~ 1),
              statistic = list(
                all_continuous() ~ "{mean} ({sd})",
                all_dichotomous() ~ "{n} ({p}%)",
                all_categorical() ~ "{n} ({p}%)",
                wmhv_2 ~ "{median} ({p25}, {p75})", 
                absuvr_2 ~ "{median} ({p25}, {p75})", 
                taumedtempsuvr_2 ~ "{median} ({p25}, {p75})"),
              label = list(
                age_1 = "Age At Baseline (Years)",
                ethnicity = "Race/Ethnicity", 
                gender_fct = "Sex/Gender",
                edu = "Education (Years)", 
                agediff12 = "Years Between Visit 1 and 2",
                hasnoinsurance = "Has No Insurance", 
                income = "Income (Dollars)", 
                socsupptot = "Social Support Score",
                smkever  = "Ever Smoker", 
                bmi = "Body Mass Index", 
                sbpavg = "Systolic Blood Pressure (mmHg)", 
                dbpavg = "Diastolic Blood Pressure (mmHg)", 
                rapa_1_total = "Rapid Assessment of Physical Activity Score, Aerobic", 
                rapa_2_total = "Rapid Assessment of Physical Activity Score, Strength and Flexibility", 
                gds_total = "Geriatric Depression Score", 
                takes_BP_meds  = "Taking Blood Pressure Medications at Baseline",
                has_htn  = "Hypertension",
                cdx_dep  = "Depression", 
                cdx_cog  = "Mild Cognitive Impairment", 
                cdx_dyslipid  = "Dyslipidemia", 
                cdx_cvd  = "Cardiovascular Disease", 
                cdx_dm  = "Diabetes",
                ldl = "LDL (mg/dL)", 
                gluc = "Glucose (mg/dL)", 
                a1c = "Hemoglobin A1c (%)", 
                egfr_nonaa = "eGFR (non-African American, mL/min/1.73m^2)", 
                egfr_aa = "eGFR (African American, mL/min/1.73m^2)", 
                choltot = "Total Cholesterol (mg/dL)",
                apoe4_positivity  = "APOE4 Allele Positive",
                wmhv_2 = "White Matter Hyperintensity Volume (cm^3)", 
                absuvr_2 = "Global Amyloid-PET SUVR", 
                taumedtempsuvr_2 = "MTL Tau-PET SUVR", 
                ctmetaroi_2 = "AD meta-ROI Cortical Thickness (mm)",
                icv_1_cm3 = "Intracranial Volume (cm^3)"),
              missing = "no")
tbl1_wmhv

# Cross-tab of race/ethnicity and HTN diagnosis among those with WMHV at visit 2
wmhv <- causmed2 %>% filter(haswmhv2 == 1)
tab_xtab(var.row = as.factor(wmhv$has_htn), 
         var.col = as.factor(wmhv$ethnicity), 
         show.row.prc = TRUE,
         show.col.prc = TRUE,
         show.na = TRUE)
```
# Table 1, for those with amyloid PET at visit 2
```{r table 1 ab, include = FALSE}
tbl1_ab <- causmed2 %>%
  filter(hasabv2_fct == "Has Amyloid-PET at Visit 2") %>% 
  tbl_summary(include = c(# demographics
                          age_1, ethnicity, gender_fct, agediff12,
                          # social
                          edu, hasnoinsurance, income, socsupptot,
                          # clinical/behavioral variables
                          smkever, bmi, sbpavg, dbpavg, rapa_1_total,
                          rapa_2_total, gds_total, takes_BP_meds, has_htn,
                          # medical history
                          cdx_dep, cdx_cog, cdx_dyslipid, cdx_cvd, cdx_dm,
                          # labs 
                          ldl, gluc, a1c, egfr_nonaa, egfr_aa, choltot,
                          apoe4_positivity,
                          # imaging vars
                          wmhv_2, absuvr_2, taumedtempsuvr_2, ctmetaroi_2,
                          icv_1_cm3),
              type = list(
                age_1 ~ "continuous",
                ethnicity ~ "categorical", 
                gender_fct ~ "categorical",
                edu ~ "continuous", 
                agediff12 ~ "continuous",
                hasnoinsurance ~ "dichotomous", 
                income ~ "continuous", 
                socsupptot ~ "continuous",
                smkever  ~ "dichotomous", 
                bmi ~ "continuous", 
                sbpavg ~ "continuous", 
                dbpavg ~ "continuous", 
                rapa_1_total ~ "continuous", 
                rapa_2_total ~ "continuous", 
                gds_total ~ "continuous", 
                takes_BP_meds  ~ "dichotomous", 
                has_htn  ~ "dichotomous",
                cdx_dep  ~ "dichotomous", 
                cdx_cog  ~ "dichotomous", 
                cdx_dyslipid  ~ "dichotomous", 
                cdx_cvd  ~ "dichotomous", 
                cdx_dm  ~ "dichotomous",
                ldl ~ "continuous", 
                gluc ~ "continuous", 
                a1c ~ "continuous", 
                egfr_nonaa ~ "continuous", 
                egfr_aa ~ "continuous", 
                choltot ~ "continuous",
                apoe4_positivity  ~ "dichotomous",
                wmhv_2 ~ "continuous", 
                absuvr_2 ~ "continuous", 
                taumedtempsuvr_2 ~ "continuous", 
                ctmetaroi_2 ~ "continuous",
                icv_1_cm3 ~ "continuous"),
              value = list(
                hasnoinsurance ~ 1, 
                takes_BP_meds ~ 1, 
                has_htn ~ 1,
                cdx_dep ~ 1, 
                cdx_cog ~ 1, 
                cdx_dyslipid ~ 1, 
                cdx_cvd ~ 1, 
                cdx_dm ~ 1,
                apoe4_positivity ~ 1),
              statistic = list(
                all_continuous() ~ "{mean} ({sd})",
                all_dichotomous() ~ "{n} ({p}%)",
                all_categorical() ~ "{n} ({p}%)",
                wmhv_2 ~ "{median} ({p25}, {p75})", 
                absuvr_2 ~ "{median} ({p25}, {p75})", 
                taumedtempsuvr_2 ~ "{median} ({p25}, {p75})"),
              label = list(
                age_1 = "Age At Baseline (Years)",
                ethnicity = "Race/Ethnicity", 
                gender_fct = "Sex/Gender",
                edu = "Education (Years)", 
                agediff12 = "Years Between Visit 1 and 2",
                hasnoinsurance = "Has No Insurance", 
                income = "Income (Dollars)", 
                socsupptot = "Social Support Score",
                smkever  = "Ever Smoker", 
                bmi = "Body Mass Index", 
                sbpavg = "Systolic Blood Pressure (mmHg)", 
                dbpavg = "Diastolic Blood Pressure (mmHg)", 
                rapa_1_total = "Rapid Assessment of Physical Activity Score, Aerobic", 
                rapa_2_total = "Rapid Assessment of Physical Activity Score, Strength and Flexibility", 
                gds_total = "Geriatric Depression Score", 
                takes_BP_meds  = "Taking Blood Pressure Medications at Baseline",
                has_htn  = "Hypertension",
                cdx_dep  = "Depression", 
                cdx_cog  = "Mild Cognitive Impairment", 
                cdx_dyslipid  = "Dyslipidemia", 
                cdx_cvd  = "Cardiovascular Disease", 
                cdx_dm  = "Diabetes",
                ldl = "LDL (mg/dL)", 
                gluc = "Glucose (mg/dL)", 
                a1c = "Hemoglobin A1c (%)", 
                egfr_nonaa = "eGFR (non-African American, mL/min/1.73m^2)", 
                egfr_aa = "eGFR (African American, mL/min/1.73m^2)", 
                choltot = "Total Cholesterol (mg/dL)",
                apoe4_positivity  = "APOE4 Allele Positive",
                wmhv_2 = "White Matter Hyperintensity Volume (cm^3)", 
                absuvr_2 = "Global Amyloid-PET SUVR", 
                taumedtempsuvr_2 = "MTL Tau-PET SUVR", 
                ctmetaroi_2 = "AD meta-ROI Cortical Thickness (mm)",
                icv_1_cm3 = "Intracranial Volume (cm^3)"),
              missing = "no")
tbl1_ab

# Cross-tab of race/ethnicity and HTN diagnosis among those with WMHV at visit 2
ab <- causmed2 %>% filter(hasabv2 == 1)
tab_xtab(var.row = as.factor(ab$has_htn), 
         var.col = as.factor(ab$ethnicity), 
         show.row.prc = TRUE,
         show.col.prc = TRUE,
         show.na = TRUE)
```
# Table 1, for those with MTL Tau-PET at visit 2
```{r table 1 wmhv, include = FALSE}
tbl1_mttau <- causmed2 %>%
  filter(hasmttau2_fct == "Has MTL Tau-PET at Visit 2") %>% 
  tbl_summary(include = c(# demographics
                          age_1, ethnicity, gender_fct, agediff12,
                          # social
                          edu, hasnoinsurance, income, socsupptot,
                          # clinical/behavioral variables
                          smkever, bmi, sbpavg, dbpavg, rapa_1_total,
                          rapa_2_total, gds_total, takes_BP_meds, has_htn,
                          # medical history
                          cdx_dep, cdx_cog, cdx_dyslipid, cdx_cvd, cdx_dm,
                          # labs 
                          ldl, gluc, a1c, egfr_nonaa, egfr_aa, choltot,
                          apoe4_positivity,
                          # imaging vars
                          wmhv_2, absuvr_2, taumedtempsuvr_2, ctmetaroi_2,
                          icv_1_cm3),
              type = list(
                age_1 ~ "continuous",
                ethnicity ~ "categorical", 
                gender_fct ~ "categorical",
                edu ~ "continuous", 
                agediff12 ~ "continuous",
                hasnoinsurance ~ "dichotomous", 
                income ~ "continuous", 
                socsupptot ~ "continuous",
                smkever  ~ "dichotomous", 
                bmi ~ "continuous", 
                sbpavg ~ "continuous", 
                dbpavg ~ "continuous", 
                rapa_1_total ~ "continuous", 
                rapa_2_total ~ "continuous", 
                gds_total ~ "continuous", 
                takes_BP_meds  ~ "dichotomous", 
                has_htn  ~ "dichotomous",
                cdx_dep  ~ "dichotomous", 
                cdx_cog  ~ "dichotomous", 
                cdx_dyslipid  ~ "dichotomous", 
                cdx_cvd  ~ "dichotomous", 
                cdx_dm  ~ "dichotomous",
                ldl ~ "continuous", 
                gluc ~ "continuous", 
                a1c ~ "continuous", 
                egfr_nonaa ~ "continuous", 
                egfr_aa ~ "continuous", 
                choltot ~ "continuous",
                apoe4_positivity  ~ "dichotomous",
                wmhv_2 ~ "continuous", 
                absuvr_2 ~ "continuous", 
                taumedtempsuvr_2 ~ "continuous", 
                ctmetaroi_2 ~ "continuous",
                icv_1_cm3 ~ "continuous"),
              value = list(
                hasnoinsurance ~ 1, 
                takes_BP_meds ~ 1, 
                has_htn ~ 1,
                cdx_dep ~ 1, 
                cdx_cog ~ 1, 
                cdx_dyslipid ~ 1, 
                cdx_cvd ~ 1, 
                cdx_dm ~ 1,
                apoe4_positivity ~ 1),
              statistic = list(
                all_continuous() ~ "{mean} ({sd})",
                all_dichotomous() ~ "{n} ({p}%)",
                all_categorical() ~ "{n} ({p}%)",
                wmhv_2 ~ "{median} ({p25}, {p75})", 
                absuvr_2 ~ "{median} ({p25}, {p75})", 
                taumedtempsuvr_2 ~ "{median} ({p25}, {p75})"),
              label = list(
                age_1 = "Age At Baseline (Years)",
                ethnicity = "Race/Ethnicity", 
                gender_fct = "Sex/Gender",
                edu = "Education (Years)", 
                agediff12 = "Years Between Visit 1 and 2",
                hasnoinsurance = "Has No Insurance", 
                income = "Income (Dollars)", 
                socsupptot = "Social Support Score",
                smkever  = "Ever Smoker", 
                bmi = "Body Mass Index", 
                sbpavg = "Systolic Blood Pressure (mmHg)", 
                dbpavg = "Diastolic Blood Pressure (mmHg)", 
                rapa_1_total = "Rapid Assessment of Physical Activity Score, Aerobic", 
                rapa_2_total = "Rapid Assessment of Physical Activity Score, Strength and Flexibility", 
                gds_total = "Geriatric Depression Score", 
                takes_BP_meds  = "Taking Blood Pressure Medications at Baseline",
                has_htn  = "Hypertension",
                cdx_dep  = "Depression", 
                cdx_cog  = "Mild Cognitive Impairment", 
                cdx_dyslipid  = "Dyslipidemia", 
                cdx_cvd  = "Cardiovascular Disease", 
                cdx_dm  = "Diabetes",
                ldl = "LDL (mg/dL)", 
                gluc = "Glucose (mg/dL)", 
                a1c = "Hemoglobin A1c (%)", 
                egfr_nonaa = "eGFR (non-African American, mL/min/1.73m^2)", 
                egfr_aa = "eGFR (African American, mL/min/1.73m^2)", 
                choltot = "Total Cholesterol (mg/dL)",
                apoe4_positivity  = "APOE4 Allele Positive",
                wmhv_2 = "White Matter Hyperintensity Volume (cm^3)", 
                absuvr_2 = "Global Amyloid-PET SUVR", 
                taumedtempsuvr_2 = "MTL Tau-PET SUVR", 
                ctmetaroi_2 = "AD meta-ROI Cortical Thickness (mm)",
                icv_1_cm3 = "Intracranial Volume (cm^3)"),
              missing = "no")
tbl1_mttau

# Cross-tab of race/ethnicity and HTN diagnosis among those with tau at visit 2
tau <- causmed2 %>% filter(hasmttauv2 == 1)
tab_xtab(var.row = as.factor(tau$has_htn), 
         var.col = as.factor(tau$ethnicity), 
         show.row.prc = TRUE,
         show.col.prc = TRUE,
         show.na = TRUE)
```

# Table 1, for those with AD meta-ROI CT at visit 2
```{r table 1 wmhv, include = FALSE}
tbl1_adct <- causmed2 %>%
  filter(hasctv2_fct == "Has AD meta-ROI CT at Visit 2") %>% 
  tbl_summary(include = c(# demographics
                          age_1, ethnicity, gender_fct, agediff12,
                          # social
                          edu, hasnoinsurance, income, socsupptot,
                          # clinical/behavioral variables
                          smkever, bmi, sbpavg, dbpavg, rapa_1_total,
                          rapa_2_total, gds_total, takes_BP_meds, has_htn,
                          # medical history
                          cdx_dep, cdx_cog, cdx_dyslipid, cdx_cvd, cdx_dm,
                          # labs 
                          ldl, gluc, a1c, egfr_nonaa, egfr_aa, choltot,
                          apoe4_positivity,
                          # imaging vars
                          wmhv_2, absuvr_2, taumedtempsuvr_2, ctmetaroi_2,
                          icv_1_cm3),
              type = list(
                age_1 ~ "continuous",
                ethnicity ~ "categorical", 
                gender_fct ~ "categorical",
                edu ~ "continuous", 
                agediff12 ~ "continuous",
                hasnoinsurance ~ "dichotomous", 
                income ~ "continuous", 
                socsupptot ~ "continuous",
                smkever  ~ "dichotomous", 
                bmi ~ "continuous", 
                sbpavg ~ "continuous", 
                dbpavg ~ "continuous", 
                rapa_1_total ~ "continuous", 
                rapa_2_total ~ "continuous", 
                gds_total ~ "continuous", 
                takes_BP_meds  ~ "dichotomous", 
                has_htn  ~ "dichotomous",
                cdx_dep  ~ "dichotomous", 
                cdx_cog  ~ "dichotomous", 
                cdx_dyslipid  ~ "dichotomous", 
                cdx_cvd  ~ "dichotomous", 
                cdx_dm  ~ "dichotomous",
                ldl ~ "continuous", 
                gluc ~ "continuous", 
                a1c ~ "continuous", 
                egfr_nonaa ~ "continuous", 
                egfr_aa ~ "continuous", 
                choltot ~ "continuous",
                apoe4_positivity  ~ "dichotomous",
                wmhv_2 ~ "continuous", 
                absuvr_2 ~ "continuous", 
                taumedtempsuvr_2 ~ "continuous", 
                ctmetaroi_2 ~ "continuous",
                icv_1_cm3 ~ "continuous"),
              value = list(
                hasnoinsurance ~ 1, 
                takes_BP_meds ~ 1, 
                has_htn ~ 1,
                cdx_dep ~ 1, 
                cdx_cog ~ 1, 
                cdx_dyslipid ~ 1, 
                cdx_cvd ~ 1, 
                cdx_dm ~ 1,
                apoe4_positivity ~ 1),
              statistic = list(
                all_continuous() ~ "{mean} ({sd})",
                all_dichotomous() ~ "{n} ({p}%)",
                all_categorical() ~ "{n} ({p}%)",
                wmhv_2 ~ "{median} ({p25}, {p75})", 
                absuvr_2 ~ "{median} ({p25}, {p75})", 
                taumedtempsuvr_2 ~ "{median} ({p25}, {p75})"),
              label = list(
                age_1 = "Age At Baseline (Years)",
                ethnicity = "Race/Ethnicity", 
                gender_fct = "Sex/Gender",
                edu = "Education (Years)", 
                agediff12 = "Years Between Visit 1 and 2",
                hasnoinsurance = "Has No Insurance", 
                income = "Income (Dollars)", 
                socsupptot = "Social Support Score",
                smkever  = "Ever Smoker", 
                bmi = "Body Mass Index", 
                sbpavg = "Systolic Blood Pressure (mmHg)", 
                dbpavg = "Diastolic Blood Pressure (mmHg)", 
                rapa_1_total = "Rapid Assessment of Physical Activity Score, Aerobic", 
                rapa_2_total = "Rapid Assessment of Physical Activity Score, Strength and Flexibility", 
                gds_total = "Geriatric Depression Score", 
                takes_BP_meds  = "Taking Blood Pressure Medications at Baseline",
                has_htn  = "Hypertension",
                cdx_dep  = "Depression", 
                cdx_cog  = "Mild Cognitive Impairment", 
                cdx_dyslipid  = "Dyslipidemia", 
                cdx_cvd  = "Cardiovascular Disease", 
                cdx_dm  = "Diabetes",
                ldl = "LDL (mg/dL)", 
                gluc = "Glucose (mg/dL)", 
                a1c = "Hemoglobin A1c (%)", 
                egfr_nonaa = "eGFR (non-African American, mL/min/1.73m^2)", 
                egfr_aa = "eGFR (African American, mL/min/1.73m^2)", 
                choltot = "Total Cholesterol (mg/dL)",
                apoe4_positivity  = "APOE4 Allele Positive",
                wmhv_2 = "White Matter Hyperintensity Volume (cm^3)", 
                absuvr_2 = "Global Amyloid-PET SUVR", 
                taumedtempsuvr_2 = "MTL Tau-PET SUVR", 
                ctmetaroi_2 = "AD meta-ROI Cortical Thickness (mm)",
                icv_1_cm3 = "Intracranial Volume (cm^3)"),
              missing = "no")
tbl1_adct

# Cross-tab of race/ethnicity and HTN diagnosis among those with adct at visit 2
ct <- causmed2 %>% filter(hasctv2 == 1)
tab_xtab(var.row = as.factor(ct$has_htn), 
         var.col = as.factor(ct$ethnicity), 
         show.row.prc = TRUE,
         show.col.prc = TRUE,
         show.na = TRUE)
```

# Merging table 1 across all samples
```{r table 1 testing, echo = T, results = 'hide'}
tbl1_everything <- tbl_merge(tbls = 
                               list(tbl1_ab,
                                    tbl1_mttau,
                                    tbl1_adct,
                                    tbl1_wmhv ),
                             tab_spanner = c("**Amyloid PET**",
                                             "**MTL-Tau**",
                                             "**AD meta-ROI CT**",
                                             "**WMHV**"))
tbl1_everything

# saving output
tbl1_everything %>%
  as_gt() %>%
  gtsave("./results/tbl1_everything.docx")

# Cross-tab of race/ethnicity and HTN diagnosis among those with any imaging at visit 2
any <- causmed2 %>% filter(haswmhv2 == 1 | hasabv2 == 1 | hasmttauv2 == 1 | hasctv2 == 1) #n=1347

tab_xtab(var.row = as.factor(any$has_htn), 
         var.col = as.factor(any$ethnicity), 
         #show.row.prc = TRUE,
         show.col.prc = TRUE,
         show.na = TRUE)

# SBP stratified by race ethnicity
describeBy(any$sbpavg, any$ethnicity)
```

